//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Card_ID { get; set; }
        public string Card_Number { get; set; }
        public string Card_Holder { get; set; }
        public int CVV { get; set; }
        public int Donor_ID { get; set; }
        public int Campaign_ID { get; set; }
        public int Payment_Method_ID { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Doner Doner { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
    }
}
