//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doner()
        {
            this.Cards = new HashSet<Card>();
            this.Payments = new HashSet<Payment>();
            this.EFTs = new HashSet<EFT>();
            this.Paypals = new HashSet<Paypal>();
        }
    
        public int Doner_ID { get; set; }
        public string Doner_Name { get; set; }
        public string Doner_Surname { get; set; }
        public string Doner_Email { get; set; }
        public string Doner_Cell { get; set; }
        public string Doner_Address { get; set; }
        public Nullable<int> City_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Cards { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFT> EFTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paypal> Paypals { get; set; }
    }
}
