//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNDonationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public decimal Payment_Amount { get; set; }
        public Nullable<int> Doner_ID { get; set; }
        public Nullable<int> Campaign_ID { get; set; }
        public Nullable<int> Payment_Method_ID { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Doner Doner { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
    }
}
